version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      GIN_MODE: ${GIN_MODE}

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    secrets:
      - db_credentials

  goose:
    build:
      context: ./database/migrations
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB=users_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin_password
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

secrets:
   db_credentials:
      file: ./secrets/db_credentials.txt