version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      GIN_MODE: ${GIN_MODE}

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_user
      - db_name

  goose:
    build:
      context: ./database/migrations
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB=users_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin_password
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_name:
    file: ./secrets/db_name.txt
    